// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {

  // 文档侧边栏
  docsSidebar: [
    'learning-paths',
    'changelog',
    {
      type: 'category',
      label: 'A2A协议',
      items: [
        'a2a/intro',
        'a2a/comprehensive-intro',
        'a2a/getting-started',
        'a2a/development',
        'a2a/github-projects',
        'a2a/best-practices',
        'a2a/faq',
        'a2a/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: 'MCP协议',
      items: [
        'mcp/intro',
        'mcp/comprehensive-intro',
        {
          type: 'category',
          label: '服务器开发',
          items: [
            'mcp/server/python-implementation',
            'mcp/server/js-implementation',
            {
              type: 'category',
              label: '开发案例',
              items: [
                'mcp/server/examples/python-examples',
                'mcp/server/examples/js-examples',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '客户端开发',
          items: [
            'mcp/client/javascript',
            'mcp/client/python',
          ],
        },
        {
          type: 'category',
          label: '实际应用案例',
          items: [
            'mcp/examples/index',
            'mcp/examples/knowledge-base-qa',
            'mcp/examples/wechat-bot',
          ],
        },
        'mcp/development',
        'mcp/practical-cases',
        'mcp/from-zero-to-one',
        'mcp/github-projects',
        'mcp/best-practices',
        'mcp/faq',
      ],
    },
    {
      type: 'category',
      label: 'n8n工作流',
      items: [
        'n8n/intro',
        'n8n/getting-started',
        'n8n/advanced-development',
        'n8n/github-projects',
        'n8n/workflow-cases',
        'n8n/best-practices',
        'n8n/faq',
        'n8n/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: 'BISHENG平台',
      items: [
        'bisheng/intro',
        'bisheng/getting-started',
        'bisheng/advanced-development',
        'bisheng/github-projects',
        'bisheng/classic-cases',
        'bisheng/best-practices',
        'bisheng/faq',
        'bisheng/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: 'Dify平台',
      items: [
        'dify/intro',
        'dify/getting-started',
        'dify/development',
        'dify/github-projects',
        'dify/best-practices',
        'dify/faq',
        'dify/practical-cases',
        'dify/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: 'MaxKB知识库',
      items: [
        'maxkb/intro',
        'maxkb/getting-started',
        'maxkb/development',
        'maxkb/github-projects',
        'maxkb/best-practices',
        'maxkb/faq',
        'maxkb/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: '多模态技术',
      items: [
        'multimodal/intro',
        'multimodal/getting-started',
        'multimodal/development',
        'multimodal/best-practices',
        'multimodal/faq',
        'multimodal/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: 'RAG技术',
      items: [
        'rag/intro',
        'rag/comprehensive-intro',
        'rag/getting-started',
        'rag/development',
        'rag/github-projects',
        'rag/best-practices',
        'rag/faq',
        'rag/practical-cases',
        'rag/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: '微调技术',
      items: [
        'finetune/intro',
        'finetune/comprehensive-intro',
        'finetune/getting-started',
        'finetune/development',
        'finetune/github-projects',
        'finetune/best-practices',
        'finetune/faq',
        'finetune/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: '大模型评测',
      items: [
        'evaluation/intro',
        'evaluation/getting-started',
        'evaluation/methods',
        'evaluation/metrics',
        'evaluation/development',
        'evaluation/best-practices',
        'evaluation/faq',
        'evaluation/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: '提示词工程',
      items: [
        'prompt/intro',
        'prompt/getting-started',
        'prompt/development',
        'prompt/github-projects',
        'prompt/best-practices',
        'prompt/faq',
        'prompt/practical-cases',
        'prompt/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label:"向量数据库",
      items:[
        'vector-database/intro',
        'vector-database/comprehensive-intro',
        'vector-database/principles',
        'vector-database/architecture',
        'vector-database/applications',
        'vector-database/mainstream',
        'vector-database/best-practices',
        'vector-database/faq',
        'vector-database/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: 'LangChain框架',
      items: [
        'langchain/intro',
        'langchain/comprehensive-intro',
        'langchain/getting-started',
        'langchain/development',
        'langchain/github-projects',
        'langchain/best-practices',
        'langchain/faq',
        'langchain/from-zero-to-one',
      ],
    },
    {
      type: 'category',
      label: 'Transformer架构',
      items: [
        'transformer/intro',
        'transformer/comprehensive-intro',
        'transformer/architecture',
        'transformer/implementation',
        'transformer/variants',
        'transformer/applications',
        'transformer/best-practices',
        'transformer/faq',
      ],
    },
  ],

  // 行业解决方案侧边栏
  solutionsSidebar: [
    'solutions/intro',
    {
      type: 'category',
      label: '智能客服解决方案',
      items: [
        'solutions/customer-service/intro',
        'solutions/customer-service/business-value',
        'solutions/customer-service/architecture',
        'solutions/customer-service/data-governance',
        'solutions/customer-service/model-management',
        'solutions/customer-service/agent-orchestration',
        'solutions/customer-service/interface-experience',
        'solutions/customer-service/quality-testing',
        'solutions/customer-service/performance-cost',
        'solutions/customer-service/monitoring',
        'solutions/customer-service/security-compliance',
        'solutions/customer-service/delivery-ops',
        'solutions/customer-service/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能文档处理解决方案',
      items: [
        'solutions/document-processing/intro',
        'solutions/document-processing/business-value',
        'solutions/document-processing/architecture',
        'solutions/document-processing/data-governance',
        'solutions/document-processing/model-management',
        'solutions/document-processing/agent-orchestration',
        'solutions/document-processing/interface-experience',
        'solutions/document-processing/quality-testing',
        'solutions/document-processing/performance-cost',
        'solutions/document-processing/monitoring',
        'solutions/document-processing/security-compliance',
        'solutions/document-processing/delivery-ops',
        'solutions/document-processing/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能代码生成解决方案',
      items: [
        'solutions/code-generation/intro',
        'solutions/code-generation/business-value',
        'solutions/code-generation/architecture',
        'solutions/code-generation/data-governance',
        'solutions/code-generation/model-management',
        'solutions/code-generation/agent-orchestration',
        'solutions/code-generation/interface-experience',
        'solutions/code-generation/quality-testing',
        'solutions/code-generation/performance-cost',
        'solutions/code-generation/monitoring',
        'solutions/code-generation/security-compliance',
        'solutions/code-generation/delivery-ops',
        'solutions/code-generation/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能营销解决方案',
      items: [
        'solutions/marketing/intro',
        'solutions/marketing/business-value',
        'solutions/marketing/architecture',
        'solutions/marketing/data-governance',
        'solutions/marketing/model-management',
        'solutions/marketing/agent-orchestration',
        'solutions/marketing/interface-experience',
        'solutions/marketing/quality-testing',
        'solutions/marketing/performance-cost',
        'solutions/marketing/monitoring',
        'solutions/marketing/security-compliance',
        'solutions/marketing/delivery-ops',
        'solutions/marketing/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能医疗解决方案',
      items: [
        'solutions/healthcare/intro',
        'solutions/healthcare/business-value',
        'solutions/healthcare/architecture',
        'solutions/healthcare/data-governance',
        'solutions/healthcare/model-management',
        'solutions/healthcare/agent-orchestration',
        'solutions/healthcare/interface-experience',
        'solutions/healthcare/quality-testing',
        'solutions/healthcare/performance-cost',
        'solutions/healthcare/monitoring',
        'solutions/healthcare/security-compliance',
        'solutions/healthcare/delivery-ops',
        'solutions/healthcare/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能教育解决方案',
      items: [
        'solutions/education/intro',
        'solutions/education/business-value',
        'solutions/education/architecture',
        'solutions/education/data-governance',
        'solutions/education/model-management',
        'solutions/education/agent-orchestration',
        'solutions/education/interface-experience',
        'solutions/education/quality-testing',
        'solutions/education/performance-cost',
        'solutions/education/monitoring',
        'solutions/education/security-compliance',
        'solutions/education/delivery-ops',
        'solutions/education/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能金融解决方案',
      items: [
        'solutions/finance/intro',
        'solutions/finance/business-value',
        'solutions/finance/architecture',
        'solutions/finance/data-governance',
        'solutions/finance/model-management',
        'solutions/finance/agent-orchestration',
        'solutions/finance/interface-experience',
        'solutions/finance/quality-testing',
        'solutions/finance/performance-cost',
        'solutions/finance/monitoring',
        'solutions/finance/security-compliance',
        'solutions/finance/delivery-ops',
        'solutions/finance/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能法律解决方案',
      items: [
        'solutions/legal/intro',
        'solutions/legal/business-value',
        'solutions/legal/architecture',
        'solutions/legal/data-governance',
        'solutions/legal/model-management',
        'solutions/legal/agent-orchestration',
        'solutions/legal/interface-experience',
        'solutions/legal/quality-testing',
        'solutions/legal/performance-cost',
        'solutions/legal/monitoring',
        'solutions/legal/security-compliance',
        'solutions/legal/delivery-ops',
        'solutions/legal/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能零售/电商解决方案',
      items: [
        'solutions/retail/intro',
        'solutions/retail/business-value',
        'solutions/retail/architecture',
        'solutions/retail/data-governance',
        'solutions/retail/model-management',
        'solutions/retail/agent-orchestration',
        'solutions/retail/interface-experience',
        'solutions/retail/quality-testing',
        'solutions/retail/performance-cost',
        'solutions/retail/monitoring',
        'solutions/retail/security-compliance',
        'solutions/retail/delivery-ops',
        'solutions/retail/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能制造/工业4.0解决方案',
      items: [
        'solutions/manufacturing/intro',
        'solutions/manufacturing/business-value',
        'solutions/manufacturing/architecture',
        'solutions/manufacturing/data-governance',
        'solutions/manufacturing/model-management',
        'solutions/manufacturing/agent-orchestration',
        'solutions/manufacturing/interface-experience',
        'solutions/manufacturing/quality-testing',
        'solutions/manufacturing/performance-cost',
        'solutions/manufacturing/monitoring',
        'solutions/manufacturing/security-compliance',
        'solutions/manufacturing/delivery-ops',
        'solutions/manufacturing/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能政务解决方案',
      items: [
        'solutions/government/intro',
        'solutions/government/business-value',
        'solutions/government/architecture',
        'solutions/government/data-governance',
        'solutions/government/model-management',
        'solutions/government/agent-orchestration',
        'solutions/government/interface-experience',
        'solutions/government/quality-testing',
        'solutions/government/performance-cost',
        'solutions/government/monitoring',
        'solutions/government/security-compliance',
        'solutions/government/delivery-ops',
        'solutions/government/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能交通解决方案',
      items: [
        'solutions/transportation/intro',
        'solutions/transportation/business-value',
        'solutions/transportation/architecture',
        'solutions/transportation/data-governance',
        'solutions/transportation/model-management',
        'solutions/transportation/agent-orchestration',
        'solutions/transportation/interface-experience',
        'solutions/transportation/quality-testing',
        'solutions/transportation/performance-cost',
        'solutions/transportation/monitoring',
        'solutions/transportation/security-compliance',
        'solutions/transportation/delivery-ops',
        'solutions/transportation/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能农业解决方案',
      items: [
        'solutions/agriculture/intro',
        'solutions/agriculture/business-value',
        'solutions/agriculture/architecture',
        'solutions/agriculture/data-governance',
        'solutions/agriculture/model-management',
        'solutions/agriculture/agent-orchestration',
        'solutions/agriculture/interface-experience',
        'solutions/agriculture/quality-testing',
        'solutions/agriculture/performance-cost',
        'solutions/agriculture/monitoring',
        'solutions/agriculture/security-compliance',
        'solutions/agriculture/delivery-ops',
        'solutions/agriculture/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能能源解决方案',
      items: [
        'solutions/energy/intro',
        'solutions/energy/business-value',
        'solutions/energy/architecture',
        'solutions/energy/data-governance',
        'solutions/energy/model-management',
        'solutions/energy/agent-orchestration',
        'solutions/energy/interface-experience',
        'solutions/energy/quality-testing',
        'solutions/energy/performance-cost',
        'solutions/energy/monitoring',
        'solutions/energy/security-compliance',
        'solutions/energy/delivery-ops',
        'solutions/energy/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能物流解决方案',
      items: [
        'solutions/logistics/intro',
        'solutions/logistics/business-value',
        'solutions/logistics/architecture',
        'solutions/logistics/data-governance',
        'solutions/logistics/model-management',
        'solutions/logistics/agent-orchestration',
        'solutions/logistics/interface-experience',
        'solutions/logistics/quality-testing',
        'solutions/logistics/performance-cost',
        'solutions/logistics/monitoring',
        'solutions/logistics/security-compliance',
        'solutions/logistics/delivery-ops',
        'solutions/logistics/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能房地产解决方案',
      items: [
        'solutions/real-estate/intro',
        'solutions/real-estate/business-value',
        'solutions/real-estate/architecture',
        'solutions/real-estate/data-governance',
        'solutions/real-estate/model-management',
        'solutions/real-estate/agent-orchestration',
        'solutions/real-estate/interface-experience',
        'solutions/real-estate/quality-testing',
        'solutions/real-estate/performance-cost',
        'solutions/real-estate/monitoring',
        'solutions/real-estate/security-compliance',
        'solutions/real-estate/delivery-ops',
        'solutions/real-estate/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能媒体/内容解决方案',
      items: [
        'solutions/media/intro',
        'solutions/media/business-value',
        'solutions/media/architecture',
        'solutions/media/data-governance',
        'solutions/media/model-management',
        'solutions/media/agent-orchestration',
        'solutions/media/interface-experience',
        'solutions/media/quality-testing',
        'solutions/media/performance-cost',
        'solutions/media/monitoring',
        'solutions/media/security-compliance',
        'solutions/media/delivery-ops',
        'solutions/media/milestones',
      ],
    },
    {
      type: 'category',
      label: '智能人力资源解决方案',
      items: [
        'solutions/hr/intro',
        'solutions/hr/business-value',
        'solutions/hr/architecture',
        'solutions/hr/data-governance',
        'solutions/hr/model-management',
        'solutions/hr/agent-orchestration',
        'solutions/hr/interface-experience',
        'solutions/hr/quality-testing',
        'solutions/hr/performance-cost',
        'solutions/hr/monitoring',
        'solutions/hr/security-compliance',
        'solutions/hr/delivery-ops',
        'solutions/hr/milestones',
      ],
    },
  ],
};

export default sidebars;
